package com.recovertogether.backend.enums;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    USER_REGISTERED,
    ACCOUNT_DELETED,
    PARTNER_REQUEST_SENT,
    PARTNER_REQUEST_ACCEPTED,
    PARTNER_REQUEST_REJECTED,
    PARTNER_UNPAIRED,
    SUPPORT_REQUEST_CREATED,
    SOS_TRIGGERED,
    LOGOUT,
    PASSWORD_CHANGED,
    ACCOUNT_LOCKED
}
