-- V1__initial_schema.sql
-- RecoverTogether Baseline Database Schema

-- 1. users
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    last_seen TIMESTAMP,
    reminder_window VARCHAR(255) DEFAULT 'ANYTIME',
    failed_login_attempts INT DEFAULT 0,
    lockout_until TIMESTAMP,
    tokens_invalidated_before TIMESTAMP,
    CONSTRAINT users_reminder_window_check CHECK (reminder_window IN ('MORNING', 'AFTERNOON', 'EVENING', 'ANYTIME'))
);

-- 2. recovery_resources
CREATE TABLE recovery_resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    category VARCHAR(50) NOT NULL,
    contact_number VARCHAR(50),
    website_url VARCHAR(255),
    email VARCHAR(100),
    operating_hours VARCHAR(100),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT recovery_resources_category_check CHECK (category IN ('CRISIS', 'COUNSELING', 'SUPPORT_GROUP', 'HEALTHCARE', 'HOTLINE', 'OTHER'))
);
CREATE INDEX idx_recovery_resource_active_category ON recovery_resources (active, category);

-- 3. refresh_tokens
CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_refresh_tokens_hash ON refresh_tokens (token_hash);
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);

-- 4. audit_logs
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(50) NOT NULL,
    user_id BIGINT,
    user_email VARCHAR(100),
    details VARCHAR(255),
    ip_address VARCHAR(45),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT audit_logs_action_check CHECK (action IN (
        'LOGIN_SUCCESS', 'LOGIN_FAILURE', 'USER_REGISTERED', 'ACCOUNT_DELETED',
        'PARTNER_REQUEST_SENT', 'PARTNER_REQUEST_ACCEPTED', 'PARTNER_REQUEST_REJECTED',
        'PARTNER_UNPAIRED', 'SUPPORT_REQUEST_CREATED', 'SOS_TRIGGERED',
        'LOGOUT', 'PASSWORD_CHANGED', 'ACCOUNT_LOCKED'
    ))
);
CREATE INDEX idx_audit_log_user_id ON audit_logs (user_id);
CREATE INDEX idx_audit_log_action ON audit_logs (action);
CREATE INDEX idx_audit_log_created_at ON audit_logs (created_at);

-- 5. check_in_reminder_schedules
CREATE TABLE check_in_reminder_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    scheduled_time TIME NOT NULL,
    sent BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP,
    CONSTRAINT uk_reminder_schedule_user_date UNIQUE (user_id, date)
);
CREATE INDEX idx_reminder_date_sent_time ON check_in_reminder_schedules (date, sent, scheduled_time);

-- 6. daily_checkins
CREATE TABLE daily_checkins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date DATE,
    status VARCHAR(255),
    note VARCHAR(500),
    created_at TIMESTAMP,
    CONSTRAINT ukgm3wopivjs8b3vhm3ab2064ox UNIQUE (user_id, date),
    CONSTRAINT daily_checkins_status_check CHECK (status IN ('SUCCESS', 'RELAPSE', 'STRUGGLING', 'STRONG_URGE', 'NEED_SUPPORT'))
);
CREATE INDEX idx_checkin_date ON daily_checkins (date);

-- 7. partner_requests
CREATE TABLE partner_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    receiver_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(255),
    created_at TIMESTAMP,
    CONSTRAINT ukr8kh8yvq8lytfrb7d7oplwdj4 UNIQUE (sender_id, receiver_id),
    CONSTRAINT partner_requests_status_check CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED'))
);

-- 8. notifications
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receiver_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type VARCHAR(255) NOT NULL,
    message VARCHAR(500) NOT NULL,
    read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP,
    CONSTRAINT notifications_type_check CHECK (type IN (
        'NEW_MESSAGE', 'SOS_ALERT', 'PARTNER_RELAPSE', 'MISSED_CHECKIN',
        'ACHIEVEMENT_UNLOCKED', 'PARTNER_ACHIEVEMENT', 'DAILY_CHECKIN_REMINDER', 'SUPPORT_REQUEST'
    ))
);
CREATE INDEX idx_notification_receiver ON notifications (receiver_id);

-- 9. messages
CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    receiver_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content VARCHAR(1000) NOT NULL,
    sos_alert BOOLEAN NOT NULL DEFAULT FALSE,
    read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_message_sender ON messages (sender_id);
CREATE INDEX idx_message_receiver ON messages (receiver_id);

-- 10. achievements
CREATE TABLE achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(255),
    earned_at TIMESTAMP,
    CONSTRAINT ukjea3nneagrxrwogrbi5yqe24q UNIQUE (user_id, title)
);
CREATE INDEX idx_achievement_user ON achievements (user_id);

-- 11. recovery_plans
CREATE TABLE recovery_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    goal VARCHAR(500),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- 12. recovery_plan_contacts (@ElementCollection)
CREATE TABLE recovery_plan_contacts (
    plan_id BIGINT NOT NULL REFERENCES recovery_plans(id) ON DELETE CASCADE,
    contact VARCHAR(255)
);

-- 13. recovery_plan_coping_strategies (@ElementCollection)
CREATE TABLE recovery_plan_coping_strategies (
    plan_id BIGINT NOT NULL REFERENCES recovery_plans(id) ON DELETE CASCADE,
    strategy VARCHAR(255)
);

-- 14. recovery_plan_triggers (@ElementCollection)
CREATE TABLE recovery_plan_triggers (
    plan_id BIGINT NOT NULL REFERENCES recovery_plans(id) ON DELETE CASCADE,
    trigger_item VARCHAR(255)
);

-- 15. support_plans
CREATE TABLE support_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- 16. support_plan_actions (@ElementCollection)
CREATE TABLE support_plan_actions (
    plan_id BIGINT NOT NULL REFERENCES support_plans(id) ON DELETE CASCADE,
    action VARCHAR(255) NOT NULL,
    PRIMARY KEY (plan_id, action),
    CONSTRAINT support_plan_actions_action_check CHECK (action IN (
        'SEND_MESSAGE', 'CALL_ME', 'ENCOURAGE_ME', 'REMIND_ME_OF_MY_GOAL',
        'REMIND_ME_OF_MY_COPING_PLAN', 'ENCOURAGE_ME_TO_CONTACT_PROFESSIONAL', 'GIVE_ME_SPACE'
    ))
);

-- 17. support_requests
CREATE TABLE support_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    partner_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    note VARCHAR(500),
    created_at TIMESTAMP
);
